services:
  algofer-client:
    container_name: algofer-client
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev

    # Set environment variables directly in the compose file
    environment:
      SERVER_URL: http://localhost:8080

    # Set environment variables based on the .env file
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - algofer-network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  algofer-network:
    driver: bridge
