FROM eclipse-temurin:21
ARG RUNNABLE_DIR=/app/oop-runner/build
 
WORKDIR /app
 
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline
 
COPY src ./src
COPY asp-runner ./runner
COPY oop-runner ./oop-runner
RUN mkdir -p $RUNNABLE_DIR
 
CMD ["./mvnw", "spring-boot:run"]
