FROM eclipse-temurin:25
 
WORKDIR /app
 
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline
 
COPY src ./src
COPY asp-runner ./runner
COPY oop-runner ./oop-runner
 
CMD ["./mvnw", "spring-boot:run"]
